name: 'Sous Admin'
description: 'A recipe that contains modules, themes, and configuration for the Sous administration experience.'
type: 'Site'
install:
  # Install core dependencies.
  - node
  # Install Gin theme and base modules that extend it.
  - gin
  - gin_toolbar
  # Install Navigation
  - navigation
  # Install Entity Usuage
  - entity_usage
  # Install Field Group and dependencies
  - field_group
  # Install Field States UI
  - field_states_ui
  # Install Login Destination
  - login_destination
  # Install Login History
  - login_history
  # Install Media Library Edit
  - media_library_edit
  # Install Publication Date
  - publication_date
  # Install Save and Edit
  - save_edit
  # Install Views AJAX History
  - views_ajax_history
  # Install Views Bulk Operations
  - views_bulk_operations
config:
  import:
    gin: '*'
    navigation: '*'
    login_destination:
      - login_destination.destination.admins_and_editors_login_destination
  actions:
    # Update entity_usage
    entity_usage.settings:
      simple_config_update:
        track_enabled_base_fields: true
        local_task_enabled_entity_types:
          - media
    # Update gin settings      -
    gin.settings:
      simple_config_update:
        preset_accent_color: 'green'
        classic_toolbar: 'horizontal'
    # Update login_destination settings
    login_destination.settings:
      simple_config_update:
        preserve_destination: TRUE
    # Update the node settings to use the admin theme.
    node.settings:
      simple_config_update:
        use_admin_theme: true
    # Update save_edit settings
    save_edit.settings:
      simple_config_update:
        button_value: ''
        button_weight: '-10'
    # Update the admin theme to Gin in Theme settings.
    system.theme:
      simple_config_update:
        admin: gin
